Revert mistaken `LIBCUDACXX_ATOMIC_VAR_INIT` change.
The `trie_mt.cpp` example doesn't use libcu++, so `LIBCUDACXX_ATOMIC_VAR_INIT` is undeclared:

    /root/cccl/libcudacxx/examples/trie_mt.cpp:39:30: error: 'LIBCUDACXX_ATOMIC_VAR_INIT' was not declared in this scope
       39 |     std::atomic<trie*> ptr = LIBCUDACXX_ATOMIC_VAR_INIT(nullptr);
          |                              ^~~~~~~~~~~~~~~~~~~~~~~~~~
    /root/cccl/libcudacxx/examples/trie_mt.cpp:41:29: error: 'LIBCUDACXX_ATOMIC_VAR_INIT' was not declared in this scope
       41 |     std::atomic_flag flag = LIBCUDACXX_ATOMIC_VAR_INIT(0);
          |                             ^~~~~~~~~~~~~~~~~~~~~~~~~~
    /root/cccl/libcudacxx/examples/trie_mt.cpp:43:28: error: 'LIBCUDACXX_ATOMIC_VAR_INIT' was not declared in this scope
       43 |   std::atomic<int> count = LIBCUDACXX_ATOMIC_VAR_INIT(0);
          |                            ^~~~~~~~~~~~~~~~~~~~~~~~~~
    gmake[2]: *** [CMakeFiles/trie_mt.dir/build.make:76: CMakeFiles/trie_mt.dir/trie_mt.cpp.o] Error 1
    gmake[1]: *** [CMakeFiles/Makefile2:117: CMakeFiles/trie_mt.dir/all] Error 2
    gmake: *** [Makefile:91: all] Error 2

This issue is introduced in PR https://github.com/NVIDIA/cccl/pull/1631
and commit 12c289218a3bac2f4490dfb40632b0028a5fd474