Also add back CUDA::nvrtc in c/parallel/test/CMakeLists.txt
https://github.com/NVIDIA/cccl/actions/runs/15143459210/job/42573304840?pr=4735

```
2025-05-20T17:04:03.5110699Z /usr/bin/ld: c/parallel/test/CMakeFiles/cccl.c.parallel.test.for.cpp.dir/test_for.cpp.o: undefined reference to symbol 'nvrtcCompileProgram@@libnvrtc.so.12'
2025-05-20T17:04:03.5111564Z /usr/bin/ld: /usr/local/cuda-12.9/targets/x86_64-linux/lib/libnvrtc.so.12: error adding symbols: DSO missing from command line
```