Fix g++-14 warning on uninitialized copying
```
In function bool cuda::std::__4::__dispatch_memmove(_Up*, _Tp*, size_t)
...
error: *(unsigned char*)(&privatized_decode_op[0]) may be used uninitialized [-Werror=maybe-uninitialized]
...
*(unsigned char*)(&privatized_decode_op[0]) was declared here
 1528 |       PrivatizedDecodeOpT privatized_decode_op[NUM_ACTIVE_CHANNELS]{};
```