[Backport 3.5] Backport #10747 and #11111 (#11201)
* [libcu++] Disable internal test due to ptxas issue (#11111)

We are getting a warning about ptxas because it cannot determine the stack space.

This is a purely internal feature with a constexpr test, so disable the test for that standard mode

Fixes nvbug6661912

* [libcu++] Improve our `to_address` implementation (#10747)

We found some issues with our current `to_address` implementation recently.

```
C:\msbuild\17\VC\Tools\MSVC\14.44.35207\include\xutility(550,46): error C2039: '->': is not a member of 'std::_Vb_iterator<std::_Wrap_alloc<std::allocator<unsigned int>>>'
            return _STD to_address(_Val.operator->()); // plain pointer overload must come first
```

The issue is that we used unqualified pointer_traits to check whether `to_address` is viable.

We cannot check for `std::pointer_traits` because it is not SFINAE friendly in many supported STL implementations until the implemented LWG-3545
We cannot check for ADL found `to_address` because we need to guard against incomplete types.