Use `cuda.bindings.path_finder` in `cuda.parallel` wheel (#4735)
* Minimal changes (proof of concept) to use `cuda.bindings.path_finder` from `cuda.parallel`

* Add cudart, nvrtc, nvjitlink to cuda_parallel dependencies in pyproject.toml

* Change `auditwheel repair` → `auditwheel show`

* Add `set -euo pipefail` to the long `bash -c` command, so that failures inside the container are not silently ignored.

* Add `nvJitLink` in c/parallel/test/CMakeLists.txt (to compensate for the changes in c/parallel/CMakeLists.txt)

* ci/matrix.yaml `override:` `build_cuda_parallel`, `test_cuda_parallel` only.

* set(CMAKE_CUDA_RUNTIME_LIBRARY "STATIC")

Co-authored-by: Marcus D. Hanwell <mhanwell@gmail.com>

* Add back `cudart` (but `static`), `nvrtc`, `nvJitLink` in c/parallel/CMakeLists.txt, remove redundant items in c/parallel/test/CMakeLists.txt

* Try different `override:`

* Remove `cudart` (dynamic) from pyproject.toml dependencies, `_load_nvidia_dynamic_library` list.

* Change `auditwheel` back to `repair`, add `--exclude` for `nvrtc`, `nvJitLink` (note: wildcards are not supported).

* Factor out ci/build_cuda_parallel_wheel.sh

* Compute EXCLUDES, to avoid hard-wiring version numbers that will surely change. Also run `shfmt -i 4`.

* Add back `patchelf` to `pip install`, to get the binary. Shuffle commands in build_cuda_parallel_wheel.sh to make the flow more clear. `pip install --upgrade pip` in ci/pyenv_helper.sh to avoid "new release of pip is available" notices.

* Manual ci/build_cuda_parallel_wheel.sh fixes

* ci/build_cuda_parallel_wheel.sh ChatGPT enhancements.

* ci/build_cuda_parallel_wheel.sh ChatGPT enhancements.

* Use auditwheel `--exclude` glob syntax.

* Pin cuda-python==12.9.0

* Restore original (full) ci/matrix.yaml

* Add comment in ci/build_cuda_parallel_wheel.sh, to refer back to build_cuda_parallel_python.sh

* install ca-certificates into devcontainer

* Reduce ci/matrix.yaml to cccl_c_parallel, python

* Add back CUDA::cudart in c/parallel/test/CMakeLists.txt (to see if this resolves the missing `#include <cuda_runtime.h>` issue)

* Add `ls -l /usr/local/cuda/targets/x86_64-linux/include` in ci/build_cccl_c_parallel.sh, for debugging.

* Testing 2025-05-20+0958

* Also add back CUDA::nvrtc in c/parallel/test/CMakeLists.txt

https://github.com/NVIDIA/cccl/actions/runs/15143459210/job/42573304840?pr=4735

```
2025-05-20T17:04:03.5110699Z /usr/bin/ld: c/parallel/test/CMakeFiles/cccl.c.parallel.test.for.cpp.dir/test_for.cpp.o: undefined reference to symbol 'nvrtcCompileProgram@@libnvrtc.so.12'
2025-05-20T17:04:03.5111564Z /usr/bin/ld: /usr/local/cuda-12.9/targets/x86_64-linux/lib/libnvrtc.so.12: error adding symbols: DSO missing from command line
```

* Change `CUDA::cudart` → `CUDA::cudart_static` in c/parallel/test/CMakeLists.txt

* Change `logging.info` → `logging.debug`

* Replace `set(CMAKE_CUDA_RUNTIME_LIBRARY "STATIC")` with `set_target_properties(... PROPERTIES CUDA_RUNTIME_LIBRARY STATIC)`

* Testing 2025-05-20+1450

* Remove debugging code from ci/build_cccl_c_parallel.sh

* Restore (full) ci/matrix.yaml from `main` branch.

* Remove `logging` in cuda_parallel/cuda/parallel/experimental/__init__.py

* Move cuda/parallel/experimental/_bindings.pyi,pyx → _bindings_impl.pyi,pyx

* Move `_load_nvidia_dynamic_library()` into _bindings.py

* Add comment in cuda_parallel/pyproject.toml (why pinned to 12.9.0)

* Rename _bindings_impl.pyi back to _bindings.pyi

* Add comment to explain preloading approach.

* Rename _bindings_impl.pyx → _cy_bindings.pyx (more informative name)

* Revert "Rename _bindings_impl.pyx → _cy_bindings.pyx (more informative name)"

This reverts commit 46cac6cdcc39c06cff08888c9e5d9249eec918cb.

---------

Co-authored-by: Marcus D. Hanwell <mhanwell@gmail.com>
Co-authored-by: Ashwin Srinath <shwina@users.noreply.github.com>