Make thrust::fill[_n] use cub::DeviceTransform (#5805)
Requires fixing a name collision with MSVC. Error message:

C:\cccl\cub\cub/device/dispatch/dispatch_transform.cuh(458): error C2220: the following warning is treated as an error
C:\cccl\cub\cub/device/dispatch/dispatch_transform.cuh(458): warning C4459: declaration of 'items_per_thread' hides global declaration
C:/cccl/cub/test/warp/catch2_test_warp_reduce.cu(33): note: see declaration of 'items_per_thread'

Fixes: #5804

Co-authored-by: Michael Schellenberger Costa <miscco@nvidia.com>